from:
  module: ./build.lib.js
  export: pages
to:
  module: '@static-pages/twig-writer'
  args:
    globals: ./build.lib.js
    functions: ./build.lib.js
    filters: ./build.lib.js
controller:
  module: ./build.lib.js
  export: controller
